### ISSUE TITLE
go-message

### ISSUE THREAD

**Issue by mooijtech** [korylprince/eml2html#1]
Hello Koryl,

Have you seen [go-message](https://github.com/emersion/go-message)?
It deals with automatic encoding and charset handling which I see extra code for in eml2html.

I would much prefer to use this library in my projects (rather than [enmime](https://github.com/jhillyerd/enmime)) because [iRedMail](https://github.com/iredmail) is a contributor and [emersion](https://github.com/emersion) has a lot more email related projects:
- [go-imap](https://github.com/emersion/go-imap)
- [go-msgauth](https://github.com/emersion/go-msgauth)
- [go-pgpmail](https://github.com/emersion/go-pgpmail)
- [go-sasl](https://github.com/emersion/go-sasl)
- [go-smtp](https://github.com/emersion/go-smtp)

Kind regards,
Marten Mooij

**Comment by korylprince** [comment]
Marten, thanks for the feedback! I've taken a look at go-message and it seems to be a bit lower-level than enmime. enmime is nice because it builds out a full mime part tree (including nested messages).

enmime actually handles charset stuff fine. The code you're seeing fixes embedded html messages. I've come across messages where the whole mime message is encoded in Windows 1252. enmime parses the message correctly, but the original email client also specified the charset as Windows 1252 in the embedded html. enmime parses everything to utf-8 (as it should), but doesn't parse and change the html itself (which it shouldn't, IMHO). The problem is really with the original client that specified the charset in both the html and the wrapper mime message. So eml2html just parses any html message and changes the chartset to utf-8 if it was specified as something else.

**Comment by mooijtech** [comment]
Thanks for the explanation, good luck with your library!
